package com.softtek.lai.module.laicheng.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.text.TextUtils;

import org.joda.time.DateTime;

/**
 * Entity mapped to table "USER_INFO_ENTITY".
 */
public class UserInfoEntity {
    public static final int USER_COACH= 1;//coach身份
    public static final int USER_FAMILY_MANAGER = 2;//家庭成员家长
    public static final int USER_FAMILY_MEMBER = 1;//家庭成员组员
    public static final int USER_FAMILY_NONE = 0;//没有

    private int id;
    /** Not-null value. */
    private String username;
    private String headimg;
    /** Not-null value. */
    private String phone;
    /** Not-null value. */
    private String birthdate;
    private int age;
    private int gender;
    private float height;
    private float weightinitial;
    private float weightgoal;
    private float weight;
    private float cycle;
    private int source;
    private int usertype;//用户类型,1,营养顾问,2,顾客
    private int familystatus;//0： 非家庭组成员 1：家庭组成员 2：家庭组管理员
    private String coachremark;
    private int coachid;
    private String expand1;
    private String expand2;
    private String expand3;
    private String expand4;
    private String expand5;

    public UserInfoEntity() {
    }

    public UserInfoEntity(int id, String username, String headimg, String phone, String birthdate, int age, int gender, float height, float weightinitial, float weightgoal, float weight, float cycle, int source, int usertype, int familystatus, String coachremark, int coachid, String expand1, String expand2, String expand3, String expand4, String expand5) {
        this.id = id;
        this.username = username;
        this.headimg = headimg;
        this.phone = phone;
        this.birthdate = birthdate;
        this.age = age;
        this.gender = gender;
        this.height = height;
        this.weightinitial = weightinitial;
        this.weightgoal = weightgoal;
        this.weight = weight;
        this.cycle = cycle;
        this.source = source;
        this.usertype = usertype;
        this.familystatus = familystatus;
        this.coachremark = coachremark;
        this.coachid = coachid;
        this.expand1 = expand1;
        this.expand2 = expand2;
        this.expand3 = expand3;
        this.expand4 = expand4;
        this.expand5 = expand5;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUsername() {
        return username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(String username) {
        this.username = username;
    }

    public String getHeadimg() {
        return headimg;
    }

    public void setHeadimg(String headimg) {
        this.headimg = headimg;
    }

    /** Not-null value. */
    public String getPhone() {
        return phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /** Not-null value. */
    public String getBirthdate() {
        return birthdate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate;
    }

    public int getAge() {
        if(age==0){
            if(!TextUtils.isEmpty(birthdate))
                try {
                    age = getAgeIntFromBirthDate(birthdate);
                } catch (Exception e) {
                    return 0;
                }
        }
        return age;
    }

    private int getAgeIntFromBirthDate(String birthdate) throws Exception {
        int age = 0;
        int year = Integer.parseInt(birthdate.substring(0, 4));
        int month = Integer.parseInt(birthdate.substring(5, 7));
        int day = Integer.parseInt(birthdate.substring(8,10));
        DateTime currentDateTime = getCurrentDateTime();
        int sysYear = currentDateTime.getYear();
        int sysMonth = currentDateTime.getMonthOfYear();
        int sysDay = currentDateTime.getDayOfMonth();
        if(year <= sysYear){
            if(month < sysMonth){
                age = sysYear - year;
            }else if(month >sysMonth){
                age = sysYear - year - 1;
            }else{
                if(day <= sysDay){
                    age = sysYear - year;
                }else{
                    age = sysYear - year - 1;
                }
            }
        }
//		String year = String.valueOf((int)(day / 365f));
        return age;
    }


    /**
     * 获取当前只有年月日的DateTIme
     */
    public static DateTime getCurrentDateTime() {
        DateTime now = new DateTime();
        return new DateTime(now.getYear(), now.getMonthOfYear(),
                now.getDayOfMonth(), 0, 0, 0);
    }

    public void setAge(int age) {
        this.age = age;
    }

    public int getGender() {
        return gender;
    }

    public void setGender(int gender) {
        this.gender = gender;
    }

    public float getHeight() {
        return height;
    }

    public void setHeight(float height) {
        this.height = height;
    }

    public float getWeightinitial() {
        return weightinitial;
    }

    public void setWeightinitial(float weightinitial) {
        this.weightinitial = weightinitial;
    }

    public float getWeightgoal() {
        return weightgoal;
    }

    public void setWeightgoal(float weightgoal) {
        this.weightgoal = weightgoal;
    }

    public float getWeight() {
        return weight;
    }

    public void setWeight(float weight) {
        this.weight = weight;
    }

    public float getCycle() {
        return cycle;
    }

    public void setCycle(float cycle) {
        this.cycle = cycle;
    }

    public int getSource() {
        return source;
    }

    public void setSource(int source) {
        this.source = source;
    }

    public int getUsertype() {
        return usertype;
    }

    public void setUsertype(int usertype) {
        this.usertype = usertype;
    }

    public int getFamilystatus() {
        return familystatus;
    }

    public void setFamilystatus(int familystatus) {
        this.familystatus = familystatus;
    }

    public String getCoachremark() {
        return coachremark;
    }

    public void setCoachremark(String coachremark) {
        this.coachremark = coachremark;
    }

    public int getCoachid() {
        return coachid;
    }

    public void setCoachid(int coachid) {
        this.coachid = coachid;
    }

    public String getExpand1() {
        return expand1;
    }

    public void setExpand1(String expand1) {
        this.expand1 = expand1;
    }

    public String getExpand2() {
        return expand2;
    }

    public void setExpand2(String expand2) {
        this.expand2 = expand2;
    }

    public String getExpand3() {
        return expand3;
    }

    public void setExpand3(String expand3) {
        this.expand3 = expand3;
    }

    public String getExpand4() {
        return expand4;
    }

    public void setExpand4(String expand4) {
        this.expand4 = expand4;
    }

    public String getExpand5() {
        return expand5;
    }

    public void setExpand5(String expand5) {
        this.expand5 = expand5;
    }


    public String getString(){
        String data = "";
        data += id;
        data += username;
        data += headimg;
        data += phone;
        data += birthdate;
        data += age;
        data += gender;
        data += height;
        data += weightinitial;
        data += weightgoal;
        data += weight;
        data += cycle;
        data += source;
        data += usertype;//用户类型,1,营养顾问,2,顾客
        data += familystatus;//0： 非家庭组成员 1：家庭组成员 2：家庭组管理员
        data += expand1;
        data += expand2;
        data += expand3;
        data += expand4;
        data += expand5;
        return data;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        UserInfoEntity that = (UserInfoEntity) o;

        return id == that.id;

    }

    @Override
    public int hashCode() {
        return id;
    }
}
